// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amkkjmxkjrfxabjurerw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFta2tqbXhranJmeGFianVyZXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzU2MTAsImV4cCI6MjA2MjAxMTYxMH0.MN3FK8RI6dVKoW9QFJUo8rlfvviOsYjxbW_5nN8iw2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);